### ISSUE TITLE
Integrate the Apron library into DepthK

### ISSUE THREAD

**Issue by lucasccordeiro** [hbgit/depthk#6]
We should evaluate the integration of the Apron library into DepthK (http://apron.cri.ensmp.fr/library/).

**Comment by WilliameRocha** [comment]
O projeto parece estar parado há pelo menos 3 anos, acho que poderíamos testar, talvez tivéssemos problemas com as dependências.

O que você acha @hbgit ?

**Comment by WilliameRocha** [comment]
Eu vi que o projeto tem interface para esta ferramenta http://bugseng.com/products/ppl/ que está em desenvolvimento inclusive com uma versão liberada neste ano.
